In [1]:
# import libraries
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline 
import seaborn as sns 
pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [2]:
hotel = pd.read_csv('./data/hotel_bookings.csv')
hotel.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  children  babies  \
0                        0                     0       2       0.0       0   
1                        0                     0       2       0.0       0   
2                        0                     1       1       0.0       0   
3                        0                     1       1       0.0       0   
4                        0                     2       2       0.0       0   

  meal country market_segment distribution_channel  is_repeated_guest  \
0   BB     PRT         Direct               Direct                  0   
1   BB     PRT         Direct               Direct                  0   
2   BB     GBR         Direct               Direct                  0   
3   BB     GBR      Corporate            Corporate                  0   
4   BB     GBR      Online TA                TA/TO                  0   

   previous_cancellations  previous_bookings_not_canceled reserved_room_type  \
0                       0                               0                  C   
1                       0                               0                  C   
2                       0                               0                  A   
3                       0                               0                  A   
4                       0                               0                  A   

  assigned_room_type  booking_changes deposit_type  agent  company  \
0                  C                3   No Deposit    NaN      NaN   
1                  C                4   No Deposit    NaN      NaN   
2                  C                0   No Deposit    NaN      NaN   
3                  A                0   No Deposit  304.0      NaN   
4                  A                0   No Deposit  240.0      NaN   

   days_in_waiting_list customer_type   adr  required_car_parking_spaces  \
0                     0     Transient   0.0                            0   
1                     0     Transient   0.0                            0   
2                     0     Transient  75.0                            0   
3                     0     Transient  75.0                            0   
4                     0     Transient  98.0                            0   

   total_of_special_requests reservation_status reservation_status_date  
0                          0          Check-Out              2015-07-01  
1                          0          Check-Out              2015-07-01  
2                          0          Check-Out              2015-07-02  
3                          0          Check-Out              2015-07-02  
4                          1          Check-Out              2015-07-03

In [3]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

## Convert dtype 

In [4]:
hotel['reservation_status_date'] = pd.to_datetime(hotel['reservation_status_date'])

## Split the data into training and test set

In [5]:
from sklearn.model_selection import train_test_split

X = hotel.drop('is_canceled', axis=1)
y = hotel['is_canceled']

train, test = train_test_split(hotel, test_size=0.3, random_state=42, stratify= y)

## EDA 

Not interested in it at this moment. 

## Data Preprocessing for ML 

In [6]:
X_train = train.drop('is_canceled', axis=1)
y_train = train['is_canceled']
X_test = test.drop('is_canceled', axis=1)
y_test = test['is_canceled']

In [7]:
X_train.head()

hotel  lead_time  arrival_date_year arrival_date_month  \
62422    City Hotel        277               2017            January   
22069  Resort Hotel         52               2016              March   
39169  Resort Hotel        183               2017             August   
6140   Resort Hotel        225               2016                May   
33105  Resort Hotel          0               2017           February   

       arrival_date_week_number  arrival_date_day_of_month  \
62422                         2                         13   
22069                        12                         15   
39169                        32                          9   
6140                         22                         26   
33105                         7                         17   

       stays_in_weekend_nights  stays_in_week_nights  adults  children  \
62422                        0                     2       2       0.0   
22069                        0                     2       2       0.0   
39169                        0                     1       2       0.0   
6140                         1                     3       1       0.0   
33105                        0                     2       2       0.0   

       babies meal country market_segment distribution_channel  \
62422       0   BB     PRT      Online TA                TA/TO   
22069       0   BB     PRT      Online TA                TA/TO   
39169       0   BB     PRT  Offline TA/TO                TA/TO   
6140        0   BB     GBR         Groups               Direct   
33105       0   BB     PRT         Direct               Direct   

       is_repeated_guest  previous_cancellations  \
62422                  0                       0   
22069                  0                       0   
39169                  0                       0   
6140                   0                       0   
33105                  1                       0   

       previous_bookings_not_canceled reserved_room_type assigned_room_type  \
62422                               0                  A                  A   
22069                               0                  A                  D   
39169                               0                  D                  E   
6140                                0                  A                  A   
33105                               1                  E                  E   

       booking_changes deposit_type  agent  company  days_in_waiting_list  \
62422                0   No Deposit    7.0      NaN                     0   
22069                0   No Deposit  240.0      NaN                     0   
39169                0   No Deposit    NaN    251.0                     0   
6140                 2   No Deposit    NaN    223.0                     0   
33105                0   No Deposit    NaN      NaN                     0   

         customer_type     adr  required_car_parking_spaces  \
62422        Transient   59.91                            0   
22069        Transient   54.00                            1   
39169  Transient-Party  141.00                            0   
6140   Transient-Party   60.00                            0   
33105        Transient    8.00                            0   

       total_of_special_requests reservation_status reservation_status_date  
62422                          0           Canceled              2016-04-11  
22069                          1          Check-Out              2016-03-17  
39169                          1          Check-Out              2017-08-10  
6140                           0          Check-Out              2016-05-30  
33105                          0          Check-Out              2017-02-19

In [8]:
num_cols = X_train.select_dtypes(include=['number']).columns.to_list()

In [9]:
def num_to_cat(df, num_col_list, n_unique_val):
    """This function takes a pandas dataframe, a list of numerical columns
    and create a list of columns that needs to be converted to categorical column if 
    it is less than or equal to n_unique_val."""
    
    # columns that needs to converted
    cols_to_convert = []
    for col in num_col_list:
        unique_val = df[col].nunique()
        print(col, unique_val)
        if unique_val <= n_unique_val:
            cols_to_convert.append(col)
    return cols_to_convert
        

In [10]:
a_list = num_to_cat(X_train, num_cols, 25)

lead_time 471
arrival_date_year 3
arrival_date_week_number 53
arrival_date_day_of_month 31
stays_in_weekend_nights 15
stays_in_week_nights 31
adults 13
children 5
babies 5
is_repeated_guest 2
previous_cancellations 15
previous_bookings_not_canceled 60
booking_changes 21
agent 316
company 323
days_in_waiting_list 119
adr 7536
required_car_parking_spaces 5
total_of_special_requests 6


In [11]:
a_list

['arrival_date_year',
 'stays_in_weekend_nights',
 'adults',
 'children',
 'babies',
 'is_repeated_guest',
 'previous_cancellations',
 'booking_changes',
 'required_car_parking_spaces',
 'total_of_special_requests']

In [12]:
# convert these columns to categorical
for col in a_list:
    X_train[col] = X_train[col].astype('category')
    X_test[col] = X_test[col].astype('category')

In [13]:
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns.to_list()
cat_cols = [col for col in cat_cols if col != 'country']

In [14]:
cat_cols

['hotel',
 'arrival_date_year',
 'arrival_date_month',
 'stays_in_weekend_nights',
 'adults',
 'children',
 'babies',
 'meal',
 'market_segment',
 'distribution_channel',
 'is_repeated_guest',
 'previous_cancellations',
 'reserved_room_type',
 'assigned_room_type',
 'booking_changes',
 'deposit_type',
 'customer_type',
 'required_car_parking_spaces',
 'total_of_special_requests',
 'reservation_status']

### Create Pipeline 

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Numerical columns pipeline
num_pipeline = Pipeline([('num_imputer', SimpleImputer(strategy='median')),
                        ('std_scaler', StandardScaler()),])

# categorical columns pipeline
cat_pipeline = Pipeline([('cat_imputer', SimpleImputer(strategy='most_frequent')),
                        ('one_hot_encoder', OneHotEncoder(sparse=False, handle_unknown='ignore')),])

# full pipeline
full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols),
])

In [16]:
X_train = full_pipeline.fit_transform(X_train)

In [17]:
X_test = full_pipeline.transform(X_test)

In [26]:
full_pipeline.named_transformers_

{'num': Pipeline(memory=None,
          steps=[('num_imputer',
                  SimpleImputer(add_indicator=False, copy=True, fill_value=None,
                                missing_values=nan, strategy='median',
                                verbose=0)),
                 ('std_scaler',
                  StandardScaler(copy=True, with_mean=True, with_std=True))],
          verbose=False),
 'cat': Pipeline(memory=None,
          steps=[('cat_imputer',
                  SimpleImputer(add_indicator=False, copy=True, fill_value=None,
                                missing_values=nan, strategy='most_frequent',
                                verbose=0)),
                 ('one_hot_encoder',
                  OneHotEncoder(categories='auto', drop=None,
                                dtype=<class 'numpy.float64'>,
                                handle_unknown='ignore', sparse=False))],
          verbose=False),
 'remainder': 'drop'}

In [29]:
# Get the list of categories generated by the one-hot-encoder
ohe_categories = full_pipeline.named_transformers_['cat']['one_hot_encoder'].categories_
ohe_categories

[array(['City Hotel', 'Resort Hotel'], dtype=object),
 array([2015, 2016, 2017], dtype=object),
 array(['April', 'August', 'December', 'February', 'January', 'July',
        'June', 'March', 'May', 'November', 'October', 'September'],
       dtype=object),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16], dtype=object),
 array([0, 1, 2, 3, 4, 5, 10, 20, 26, 27, 40, 50, 55], dtype=object),
 array([0.0, 1.0, 2.0, 3.0, 10.0], dtype=object),
 array([0, 1, 2, 9, 10], dtype=object),
 array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object),
 array(['Aviation', 'Complementary', 'Corporate', 'Direct', 'Groups',
        'Offline TA/TO', 'Online TA', 'Undefined'], dtype=object),
 array(['Corporate', 'Direct', 'GDS', 'TA/TO', 'Undefined'], dtype=object),
 array([0, 1], dtype=object),
 array([0, 1, 2, 3, 4, 5, 6, 11, 13, 14, 19, 21, 24, 25, 26], dtype=object),
 array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'L', 'P'], dtype=object),
 array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', '

In [30]:
# Create nice names for our one hot encoded features
new_ohe_features = [f"{col}__{val}" for col, vals in zip(cat_cols, ohe_categories) for val in vals]
new_ohe_features

['hotel__City Hotel',
 'hotel__Resort Hotel',
 'arrival_date_year__2015',
 'arrival_date_year__2016',
 'arrival_date_year__2017',
 'arrival_date_month__April',
 'arrival_date_month__August',
 'arrival_date_month__December',
 'arrival_date_month__February',
 'arrival_date_month__January',
 'arrival_date_month__July',
 'arrival_date_month__June',
 'arrival_date_month__March',
 'arrival_date_month__May',
 'arrival_date_month__November',
 'arrival_date_month__October',
 'arrival_date_month__September',
 'stays_in_weekend_nights__0',
 'stays_in_weekend_nights__1',
 'stays_in_weekend_nights__2',
 'stays_in_weekend_nights__3',
 'stays_in_weekend_nights__4',
 'stays_in_weekend_nights__5',
 'stays_in_weekend_nights__6',
 'stays_in_weekend_nights__7',
 'stays_in_weekend_nights__8',
 'stays_in_weekend_nights__9',
 'stays_in_weekend_nights__10',
 'stays_in_weekend_nights__12',
 'stays_in_weekend_nights__13',
 'stays_in_weekend_nights__14',
 'stays_in_weekend_nights__16',
 'adults__0',
 'adults__1'

In [31]:
# Create a new list with all names of features
all_features = num_cols + new_ohe_features
all_features

['lead_time',
 'arrival_date_year',
 'arrival_date_week_number',
 'arrival_date_day_of_month',
 'stays_in_weekend_nights',
 'stays_in_week_nights',
 'adults',
 'children',
 'babies',
 'is_repeated_guest',
 'previous_cancellations',
 'previous_bookings_not_canceled',
 'booking_changes',
 'agent',
 'company',
 'days_in_waiting_list',
 'adr',
 'required_car_parking_spaces',
 'total_of_special_requests',
 'hotel__City Hotel',
 'hotel__Resort Hotel',
 'arrival_date_year__2015',
 'arrival_date_year__2016',
 'arrival_date_year__2017',
 'arrival_date_month__April',
 'arrival_date_month__August',
 'arrival_date_month__December',
 'arrival_date_month__February',
 'arrival_date_month__January',
 'arrival_date_month__July',
 'arrival_date_month__June',
 'arrival_date_month__March',
 'arrival_date_month__May',
 'arrival_date_month__November',
 'arrival_date_month__October',
 'arrival_date_month__September',
 'stays_in_weekend_nights__0',
 'stays_in_weekend_nights__1',
 'stays_in_weekend_nights__2',

In [32]:
# Create pandas dataframe 
X_train = pd.DataFrame(X_train, columns=all_features)
X_test = pd.DataFrame(X_test, columns=all_features)

In [33]:
X_train.head()

lead_time  arrival_date_year  arrival_date_week_number  \
0   1.621377           1.196107                 -1.845449   
1  -0.484046          -0.218847                 -1.111426   
2   0.741778           1.196107                  0.356620   
3   1.134790          -0.218847                 -0.377403   
4  -0.970633           1.196107                 -1.478438   

   arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  \
0                  -0.317376                -0.930469             -0.262270   
1                  -0.089892                -0.930469             -0.262270   
2                  -0.772344                -0.930469             -0.788453   
3                   1.161271                 0.073288              0.263913   
4                   0.137592                -0.930469             -0.262270   

     adults  children   babies  is_repeated_guest  previous_cancellations  \
0  0.241661 -0.259311 -0.07784          -0.181032               -0.103327   
1  0.241661 -0.259311 -0.07784          -0.181032               -0.103327   
2  0.241661 -0.259311 -0.07784          -0.181032               -0.103327   
3 -1.432020 -0.259311 -0.07784          -0.181032               -0.103327   
4  0.241661 -0.259311 -0.07784           5.523875               -0.103327   

   previous_bookings_not_canceled  booking_changes     agent   company  \
0                       -0.092341        -0.333949 -0.658396 -0.019839   
1                       -0.092341        -0.333949  1.548862 -0.019839   
2                       -0.092341        -0.333949 -0.592084  2.289756   
3                       -0.092341         2.690280 -0.592084  1.403884   
4                        0.577090        -0.333949 -0.592084 -0.019839   

   days_in_waiting_list       adr  required_car_parking_spaces  \
0              -0.13386 -0.814661                    -0.252811   
1              -0.13386 -0.929866                     3.862536   
2              -0.13386  0.766042                    -0.252811   
3              -0.13386 -0.812907                    -0.252811   
4              -0.13386 -1.826554                    -0.252811   

   total_of_special_requests  hotel__City Hotel  hotel__Resort Hotel  \
0                  -0.718769                1.0                  0.0   
1                   0.543835                0.0                  1.0   
2                   0.543835                0.0                  1.0   
3                  -0.718769                0.0                  1.0   
4                  -0.718769                0.0                  1.0   

   arrival_date_year__2015  arrival_date_year__2016  arrival_date_year__2017  \
0                      0.0                      0.0                      1.0   
1                      0.0                      1.0                      0.0   
2                      0.0                      0.0                      1.0   
3                      0.0                      1.0                      0.0   
4                      0.0                      0.0                      1.0   

   arrival_date_month__April  arrival_date_month__August  \
0                        0.0                         0.0   
1                        0.0                         0.0   
2                        0.0                         1.0   
3                        0.0                         0.0   
4                        0.0                         0.0   

   arrival_date_month__December  arrival_date_month__February  \
0                           0.0                           0.0   
1                           0.0                           0.0   
2                           0.0                           0.0   
3                           0.0                           0.0   
4                           0.0                           1.0   

   arrival_date_month__January  arrival_date_month__July  \
0                          1.0                       0.0   
1                          0.0                       0.0   
2         

In [38]:
X_test.head()

lead_time  arrival_date_year  arrival_date_week_number  \
0  -0.970633          -0.218847                  0.430023   
1   0.367480           1.196107                 -0.671012   
2   1.406156           1.196107                  0.356620   
3   0.554629          -0.218847                  0.723632   
4  -0.951918          -0.218847                 -0.157196   

   arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  \
0                  -0.999829                 0.073288             -1.314635   
1                  -1.341055                -0.930469             -0.262270   
2                  -0.431118                 1.077046              1.316279   
3                  -0.658602                 1.077046              1.316279   
4                   0.137592                -0.930469             -0.262270   

     adults  children   babies  is_repeated_guest  previous_cancellations  \
0  0.241661 -0.259311 -0.07784          -0.181032               -0.103327   
1  0.241661 -0.259311 -0.07784          -0.181032               -0.103327   
2  0.241661  4.794055 -0.07784          -0.181032               -0.103327   
3  0.241661 -0.259311 -0.07784          -0.181032               -0.103327   
4  0.241661 -0.259311 -0.07784          -0.181032               -0.103327   

   previous_bookings_not_canceled  booking_changes     agent   company  \
0                       -0.092341        -0.333949 -0.639450 -0.019839   
1                       -0.092341        -0.333949 -0.194209 -0.019839   
2                       -0.092341         1.178166  2.249879 -0.019839   
3                       -0.092341        -0.333949 -0.592084 -0.019839   
4                       -0.092341        -0.333949 -0.592084 -0.019839   

   days_in_waiting_list       adr  required_car_parking_spaces  \
0              -0.13386 -0.072165                    -0.252811   
1              -0.13386  0.356685                    -0.252811   
2              -0.13386  2.161366                    -0.252811   
3              -0.13386 -0.093998                    -0.252811   
4              -0.13386  0.727056                    -0.252811   

   total_of_special_requests  hotel__City Hotel  hotel__Resort Hotel  \
0                   0.543835                1.0                  0.0   
1                  -0.718769                1.0                  0.0   
2                   0.543835                0.0                  1.0   
3                  -0.718769                1.0                  0.0   
4                   0.543835                1.0                  0.0   

   arrival_date_year__2015  arrival_date_year__2016  arrival_date_year__2017  \
0                      0.0                      1.0                      0.0   
1                      0.0                      0.0                      1.0   
2                      0.0                      0.0                      1.0   
3                      0.0                      1.0                      0.0   
4                      0.0                      1.0                      0.0   

   arrival_date_month__April  arrival_date_month__August  \
0                        0.0                         1.0   
1                        0.0                         0.0   
2                        0.0                         1.0   
3                        0.0                         0.0   
4                        0.0                         0.0   

   arrival_date_month__December  arrival_date_month__February  \
0                           0.0                           0.0   
1                           0.0                           0.0   
2                           0.0                           0.0   
3                           0.0                           0.0   
4                           0.0                           0.0   

   arrival_date_month__January  arrival_date_month__July  \
0                          0.0                       0.0   
1                          0.0                       0.0   
2         

In [36]:
X_test.shape

(35817, 173)

In [37]:
X_train.shape

(83573, 173)

# Build Model

In [39]:
# build a Logitic Regression model

from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
log_reg_predictions = log_reg.predict(X_train)

In [40]:
# measure accuracy
from sklearn.model_selection import cross_val_score
cross_val_score(log_reg, X_train, y_train, cv=3, scoring="accuracy")

array([1., 1., 1.])

In [42]:
from sklearn.model_selection import cross_val_predict
log_reg_pred = cross_val_predict(log_reg, X_train, y_train, cv=3)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, log_reg_pred)

array([[52616,     0],
       [    0, 30957]])

In [58]:
final_predictions = log_reg.predict(X_test)
confusion_matrix(y_test, final_predictions)

array([[22550,     0],
       [    0, 13267]])

The accuracy on the test set is 100% as we can see there is no error. 